plugins {
    id 'com.android.application'
}

android {
    namespace 'org.asiaflix.clean'
    compileSdk 35

    defaultConfig {
        applicationId 'org.asiaflix.clean'
        minSdk 26
        targetSdk 35
        versionCode 4
        versionName '1.3.0'
    }

    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
            signingConfig signingConfigs.debug
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
